<?php
$products = [
    ["name" => "Cloud II Wireless - Gaming Headset", "price" => "84,99$", "imageSrc" => "img/hyperxred-Photoroom.png-Photoroom.png"],
    ["name" => "Cloud II Wireless - Gaming Headset", "price" => "84,99$", "imageSrc" => "img/hyperxred-Photoroom.png-Photoroom.png"],
    ["name" => "Cloud II Wireless - Gaming Headset", "price" => "84,99$", "imageSrc" => "img/hyperxred-Photoroom.png-Photoroom.png"],
    ["name" => "Cloud II Wireless - Gaming Headset", "price" => "84,99$", "imageSrc" => "img/hyperxred-Photoroom.png-Photoroom.png"],
    ["name" => "Cloud II Wireless - Gaming Headset", "price" => "84,99$", "imageSrc" => "img/hyperxred-Photoroom.png-Photoroom.png"],
    ["name" => "Cloud II Wireless - Gaming Headset", "price" => "84,99$", "imageSrc" => "img/hyperxred-Photoroom.png-Photoroom.png"],
    ["name" => "Cloud II Wireless - Gaming Headset", "price" => "84,99$", "imageSrc" => "img/hyperxred-Photoroom.png-Photoroom.png"],
    ["name" => "Cloud II Wireless - Gaming Headset", "price" => "84,99$", "imageSrc" => "img/hyperxred-Photoroom.png-Photoroom.png"],
    ["name" => "Cloud II Wireless - Gaming Headset", "price" => "84,99$", "imageSrc" => "img/hyperxred-Photoroom.png-Photoroom.png"],
    ["name" => "Cloud II Wireless - Gaming Headset", "price" => "84,99$", "imageSrc" => "img/hyperxred-Photoroom.png-Photoroom.png"],
    ["name" => "Cloud II Wireless - Gaming Headset", "price" => "84,99$", "imageSrc" => "img/hyperxred-Photoroom.png-Photoroom.png"],
    ["name" => "Cloud II Wireless - Gaming Headset", "price" => "84,99$", "imageSrc" => "img/hyperxred-Photoroom.png-Photoroom.png"],
    ["name" => "Cloud II Wireless - Gaming Headset", "price" => "84,99$", "imageSrc" => "img/hyperxred-Photoroom.png-Photoroom.png"],
    ["name" => "Cloud II Wireless - Gaming Headset", "price" => "84,99$", "imageSrc" => "img/hyperxred-Photoroom.png-Photoroom.png"],
    ["name" => "Cloud II Wireless - Gaming Headset", "price" => "84,99$", "imageSrc" => "img/hyperxred-Photoroom.png-Photoroom.png"],
    ["name" => "Cloud II Wireless - Gaming Headset", "price" => "84,99$", "imageSrc" => "img/hyperxred-Photoroom.png-Photoroom.png"],
    ["name" => "Cloud II Wireless - Gaming Headset", "price" => "84,99$", "imageSrc" => "img/hyperxred-Photoroom.png-Photoroom.png"],
    ["name" => "Cloud II Wireless - Gaming Headset", "price" => "84,99$", "imageSrc" => "img/hyperxred-Photoroom.png-Photoroom.png"],
    ["name" => "Cloud II Wireless - Gaming Headset", "price" => "84,99$", "imageSrc" => "img/hyperxred-Photoroom.png-Photoroom.png"],
    ["name" => "Cloud II Wireless - Gaming Headset", "price" => "84,99$", "imageSrc" => "img/hyperxred-Photoroom.png-Photoroom.png"],
    ["name" => "Cloud II Wireless - Gaming Headset", "price" => "84,99$", "imageSrc" => "img/hyperxred-Photoroom.png-Photoroom.png"],
];
?>
